#mtl
${local_namespace("packages.busybox")}

${Package("$(PACKAGES_BUILD_DIR)/busybox-$(PACKAGES_BUSYBOX_VERSION)", "", "1.18.4", "http://busybox.net/downloads/busybox-$(PACKAGES_BUSYBOX_VERSION).tar.bz2", "$(ROOTFS_DIR)/bin/busybox")}


#${package("$(PACKAGES_BUILD_DIR)/busybox-$(PACKAGES_BUSYBOX_VERSION)", "", "1.18.4", "busybox-$(PACKAGES_BUSYBOX_VERSION).tar.bz2", "http://busybox.net/downloads/$(PACKAGES_BUSYBOX_FILE)")}

${DownloadRule("$(PACKAGES_BUSYBOX_URL)")}

${UnpackRule("$(DOWNLOAD_DIR)/$(PACKAGES_BUSYBOX_FILE)", "$(PACKAGES_BUILD_DIR)", "$(PACKAGES_BUSYBOX_SRC_DIR)/Makefile")}

${local()}CONFIG := $(PACKAGES_BUSYBOX_BUILD_DIR)/.config
$(PACKAGES_BUSYBOX_CONFIG): $(PACKAGES_BUSYBOX_SRC_DIR)/Makefile $(TARGET_BUSYBOX_CONFIG) 	
	$(CP) -a $(TARGET_BUSYBOX_CONFIG) $(PACKAGES_BUSYBOX_BUILD_DIR)/.config
	$(PACKAGES_ENV) $(MAKE) -C $(PACKAGES_BUSYBOX_BUILD_DIR) oldconfig

${local()}DEPMOD := $(ROOTFS_DIR)/sbin/depmod.pl
$(PACKAGES_BUSYBOX_DEPMOD): $(PACKAGES_BUSYBOX_SRC_DIR)/Makefile
	$(CP) "$(PACKAGES_BUSYBOX_SRC_DIR)/examples/depmod.pl" $(PACKAGES_BUSYBOX_DEPMOD)
	
PACKAGES_BUSYBOX_BUILD =  $(PACKAGES_BUSYBOX_BUILD_DIR)/busybox
$(PACKAGES_BUSYBOX_BUILD): $(PACKAGES_BUSYBOX_CONFIG)
	$(PACKAGES_ENV) $(MAKE) ARCH=$(KERNEL_ARCH) CROSS_COMPILE=$(ARCH_TARGET)- CC="$(ARCH_TARGET)-gcc" -C $(PACKAGES_BUSYBOX_BUILD_DIR) all

PACKAGES_BUSYBOX_INSTALL =  $(ROOTFS_DIR)/bin/busybox
$(PACKAGES_BUSYBOX_INSTALL): $(PACKAGES_BUSYBOX_BUILD)
	$(PACKAGES_ENV)  $(MAKE) ARCH=$(KERNEL_ARCH) CROSS_COMPILE=$(ARCH_TARGET)- CC="$(ARCH_TARGET)-gcc"  CONFIG_PREFIX=$(ROOTFS_DIR) -C $(PACKAGES_BUSYBOX_BUILD_DIR) install
	
$(ROOTFS_DIR)/etc/network/udhcpc.script:
	$(CP) $(ROOT)/${namespace.current.replace(".", "/")}/udhcpc-default.script $(ROOTFS_DIR)/etc/network/udhcpc.script

busybox-menuconfig:
	$(PACKAGES_ENV) $(MAKE) -C $(PACKAGES_BUSYBOX_BUILD_DIR) ARCH=$(KERNEL_ARCH) CROSS_COMPILE=$(ARCH_TARGET)-  CC="$(ARCH_TARGET)-gcc" menuconfig
	
	
.NOTPARALLEL: