#mtl
${local_namespace("packages.kernel-rpi")}

${Package("$(PACKAGES_BUILD_DIR)/linux-$(PACKAGES_KERNEL-RPI_VERSION)", "", "3.10.y", "https://github.com/raspberrypi/linux.git", "$(ROOTFS_DIR)/boot/kernel-$(PACKAGES_KERNEL_VERSION)")}

${Rule('$(PACKAGES_KERNEL-RPI_SRC_DIR)/Makefile', "$(TOOLCHAIN_KERNEL-HEADERS-RPI_DOWNLOAD)", rule_var_name=var_name("copy-src"))}
	$(MKDIR) $(PACKAGES_KERNEL-RPI_SRC_DIR)
	$(CP) -R $(DOWNLOAD_DIR)/linux/* $(PACKAGES_KERNEL-RPI_SRC_DIR)

${Rule('$(PACKAGES_KERNEL-RPI_BUILD_DIR)/.config', "$(TARGET_KERNEL_CONFIG)", rule_var_name=var_name("copy-config"))}
	$(MAKE) -C $(PACKAGES_KERNEL-RPI_BUILD_DIR) mrproper
	$(CP) -a $(TARGET_KERNEL_CONFIG) $(PACKAGES_KERNEL-RPI_BUILD_DIR)/.config

${Rule('$(PACKAGES_KERNEL-RPI_BUILD_DIR)/vmlinux', "$(PACKAGES_KERNEL-RPI_COPY-SRC) $(PACKAGES_KERNEL-RPI_COPY-CONFIG)", rule_var_name=var_name("build"))}
	$(PACKAGES_ENV) KERNEL_SRC=$(PACKAGES_KERNEL-RPI_BUILD_DIR) CCPREFIX=$(TOOLCHAIN_ROOT_DIR)/bin/$(ARCH_TARGET)- $(MAKE) -C $(PACKAGES_KERNEL-RPI_BUILD_DIR) ARCH=$(KERNEL_ARCH) CROSS_COMPILE=$(ARCH_TARGET)- oldconfig
	$(PACKAGES_ENV) $(MAKE) -C $(PACKAGES_KERNEL-RPI_BUILD_DIR) ARCH=$(KERNEL_ARCH) CROSS_COMPILE=$(ARCH_TARGET)-

include packages/busybox.mk
	
${Rule('$(ROOTFS_DIR)/boot/kernel-$(PACKAGES_KERNEL-RPI_VERSION)', "$(PACKAGES_KERNEL-RPI_BUILD) $(ROOTFS_DIR)/sbin/depmod.pl", rule_var_name=var_name("install"))}
	$(CP) $(PACKAGES_KERNEL-RPI_BUILD_DIR)/System.map $(ROOTFS_DIR)/boot/System.map-$(PACKAGES_KERNEL-RPI_VERSION)
	$(CP) $(PACKAGES_KERNEL-RPI_BUILD_DIR)/arch/$(TARGET)/boot/bzImage $(ROOTFS_DIR)/boot/kernel-$(PACKAGES_KERNEL-RPI_VERSION)
	$(CP) $(PACKAGES_KERNEL-RPI_BUILD_DIR)/.config $(ROOTFS_DIR)/boot/config-$(PACKAGES_KERNEL-RPI_VERSION)
ifdef STRIP_TARGET	
	$(TOOLCHAIN_ENV) $(MAKE) -C $(PACKAGES_KERNEL-RPI_BUILD_DIR) ARCH=$(KERNEL_ARCH) CROSS_COMPILE=$(ARCH_TARGET)- modules_install INSTALL_MOD_PATH=$(ROOTFS_DIR) INSTALL_MOD_STRIP=1
else
	$(TOOLCHAIN_ENV) $(MAKE) -C $(PACKAGES_KERNEL-RPI_BUILD_DIR) ARCH=$(KERNEL_ARCH) CROSS_COMPILE=$(ARCH_TARGET)- modules_install INSTALL_MOD_PATH=$(ROOTFS_DIR)
endif
	$(ROOTFS_DIR)/sbin/depmod.pl -F $(ROOTFS_DIR)/boot/System.map-$(PACKAGES_KERNEL-RPI_VERSION) -b $(ROOTFS_DIR)/lib/modules/$(PACKAGES_KERNEL-RPI_VERSION)

kernel-menuconfig:
	$(PACKAGES_ENV) $(MAKE) -C $(PACKAGES_KERNEL-RPI_BUILD_DIR) ARCH=$(KERNEL_ARCH) CROSS_COMPILE=$(ARCH_TARGET)- menuconfig


.NOTPARALLEL: