#mtl
${local_namespace("toolchain.kernel-headers")}

#${package("$(TOOLCHAIN_BUILD_DIR)/linux-$(TOOLCHAIN_KERNEL-HEADERS_VERSION)", "", "2.6.39", "linux-$(TOOLCHAIN_KERNEL-HEADERS_VERSION).tar.bz2", "http://linux-kernel.uio.no/pub/linux/kernel/v2.6/$(TOOLCHAIN_KERNEL-HEADERS_FILE)")}

${Package('$(TOOLCHAIN_BUILD_DIR)/linux-$(TOOLCHAIN_KERNEL-HEADERS_VERSION)', '', '2.6.39', "http://linux-kernel.uio.no/pub/linux/kernel/v2.6/linux-$(TOOLCHAIN_KERNEL-HEADERS_VERSION).tar.bz2", "$(ROOTFS_DIR)/usr/include/linux/fs.h")}

${DownloadRule("$(TOOLCHAIN_KERNEL-HEADERS_URL)")}

${UnpackRule("$(DOWNLOAD_DIR)/$(TOOLCHAIN_KERNEL-HEADERS_FILE)", "$(TOOLCHAIN_BUILD_DIR)", "$(TOOLCHAIN_KERNEL-HEADERS_BUILD_DIR)/Makefile")}

#${download()}

#${unpack("$(TOOLCHAIN_BUILD_DIR)", "$(TOOLCHAIN_KERNEL-HEADERS_SRC_DIR)/Makefile")}

TOOLCHAIN_KERNEL-HEADERS_BUILD = $(TOOLCHAIN_KERNEL-HEADERS_SRC_DIR)/include/linux/version.h
$(TOOLCHAIN_KERNEL-HEADERS_BUILD): $(TOOLCHAIN_KERNEL-HEADERS_BUILD_DIR)/Makefile
	CFLAGS="" CXXFLAGS="" $(MAKE) -C $(TOOLCHAIN_KERNEL-HEADERS_BUILD_DIR) mrproper
	CFLAGS="" CXXFLAGS="" $(MAKE) -C $(TOOLCHAIN_KERNEL-HEADERS_BUILD_DIR) ARCH=$(KERNEL_ARCH) headers_check

TOOLCHAIN_KERNEL-HEADERS_INSTALL = $(ROOTFS_DIR)/usr/include/linux/fs.h 
$(TOOLCHAIN_KERNEL-HEADERS_INSTALL): $(TOOLCHAIN_KERNEL-HEADERS_SRC_DIR)/include/linux/version.h
	CFLAGS="" CXXFLAGS="" $(MAKE) -C $(TOOLCHAIN_KERNEL-HEADERS_BUILD_DIR) ARCH=$(KERNEL_ARCH) INSTALL_HDR_PATH=$(ROOTFS_DIR)/usr headers_install

.NOTPARALLEL: